remote_theme: ngzhio/jekyll-theme-hamilton
plugins:
  - jekyll-remote-theme
title: Henry Murdock
description: Software engineer focused on computational physics, high-performance computing, and machine learning systems.
author: Henry Murdock
email: henrygm3@illinois.edu
avatar: /profile_pic.jpg
